### One Hot Encoding - sklearn

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# sklearn
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [2]:
# load titanic dataset

usecols = ["Pclass", "SibSp", "Parch", "Gender", "Embarked", "Cabin", "Survived"]
file_url = "https://raw.githubusercontent.com/cmps460s26/cmps460-content/refs/heads/main/examples/02.eda/datasets/titanic.csv"
data = pd.read_csv(file_url, usecols=usecols)
data["Cabin"] = data["Cabin"].str[0]

data.head()

   Survived  Pclass  Gender  SibSp  Parch Cabin Embarked
0         0       3    male      1      0   NaN        S
1         1       1  female      1      0     C        C
2         1       3  female      0      0   NaN        S
3         1       1  female      1      0     C        S
4         0       3    male      0      0   NaN        S

### Split into Train and Test before encoding

Just like imputation, all methods of categorical encoding should be performed over the training set, and then propagated to the test set.

In [3]:
# let's separate into training and testing set

X_train, X_test, y_train, y_test = train_test_split(
    data.drop("Survived", axis=1),  # predictors
    data["Survived"],  # target
    test_size=0.3,  # percentage of obs in test set
    random_state=0,
)  # seed to ensure reproducibility

X_train.shape, X_test.shape

((623, 6), (268, 6))

In [4]:
# To start, we fillna manually. Later on
# we add this step to a pipeline

X_train.fillna("Missing", inplace=True)
X_test.fillna("Missing", inplace=True)

In [5]:
# set up encoder
# sparse_output=False -> All 0/1 columns are stored explicitly
encoder = OneHotEncoder(sparse_output=False)
encoder.set_output(transform="pandas")

OneHotEncoder(sparse_output=False)

In [6]:
# fit the encoder (finds categories)

encoder.fit(X_train)

OneHotEncoder(sparse_output=False)

In [8]:
# we observe the learned categories
encoder.categories_

[array([1, 2, 3]),
 array(['female', 'male'], dtype=object),
 array([0, 1, 2, 3, 4, 5, 8]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'Missing', 'T'], dtype=object),
 array(['C', 'Missing', 'Q', 'S'], dtype=object)]

In [9]:
# transform the data sets

X_train_enc = encoder.transform(X_train)
X_test_enc = encoder.transform(X_test)

X_train_enc.head()

,Pclass_1,Pclass_2,Pclass_3,Gender_female,Gender_male,SibSp_0,SibSp_1,SibSp_2,SibSp_3,SibSp_4,...,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_Missing,Cabin_T,Embarked_C,Embarked_Missing,Embarked_Q,Embarked_S
857,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
52,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
386,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
124,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
578,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [10]:
# we can retrieve the feature names as follows:

encoder.get_feature_names_out()

array(['Pclass_1', 'Pclass_2', 'Pclass_3', 'Gender_female', 'Gender_male',
       'SibSp_0', 'SibSp_1', 'SibSp_2', 'SibSp_3', 'SibSp_4', 'SibSp_5',
       'SibSp_8', 'Parch_0', 'Parch_1', 'Parch_2', 'Parch_3', 'Parch_4',
       'Parch_5', 'Parch_6', 'Cabin_A', 'Cabin_B', 'Cabin_C', 'Cabin_D',
       'Cabin_E', 'Cabin_F', 'Cabin_G', 'Cabin_Missing', 'Cabin_T',
       'Embarked_C', 'Embarked_Missing', 'Embarked_Q', 'Embarked_S'],
      dtype=object)